# Generated by Django 5.2.8 on 2025-12-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_meal_ingrediententry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('portion', models.CharField(blank=True, default='100g', max_length=200)),
                ('weight_grams', models.FloatField(default=100.0)),
                ('calories', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('country', models.CharField(default='Brasil', max_length=80)),
                ('languages', models.CharField(default='pt', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
